export const BAIRROS_BELEM = [
  "Aeronáutica",
  "Águas Lindas",
  "Águas Negras",
  "Agulha",
  "Ariramba",
  "Atalaia",
  "Aurá",
  "Baía do Sol",
  "Barreiro",
  "Batista Campos",
  "Benguí",
  "Bonfim",
  "Cabanagem",
  "Campina",
  "Canudos",
  "Carananduba",
  "Castanheira",
  "Chapéu Virado",
  "Cidade Velha",
  "Coqueiro",
  "Condor",
  "Cremação",
  "Cruzeiro",
  "Curió-Utinga",
  "Farol",
  "Fátima",
  "Guamá",
  "Guanabara",
  "ltaiteua",
  "Jurunas",
  "Mangueirão",
  "Maracacuera",
  "Maracajá",
  "Marambaia",
  "Marco",
  "Miramar",
  "Montese (Terra Firme)",
  "Murubira",
  "Natal do Murubira",
  "Nazaré",
  "Paracuri",
  "Paraíso",
  "Parque Guajará",
  "Parque Verde",
  "Passagem Vermelha",
  "Pedreira",
  "Ponta Grossa",
  "Porto Arthur",
  "Pratinha",
  "Praia Grande",
  "Reduto",
  "Sacramenta",
  "Santa Cruz",
  "São Brás",
  "São Francisco",
  "São João do Outeiro",
  "Souza",
  "Tapanã",
  "Telégrafo",
  "Tenoné",
  "Terra Firme",
  "Umarizal",
  "Una",
  "Universidade",
  "Val-de-Cães",
  "Vila"
].sort();

export const GENDERS = [
  { value: "Masculino", label: "Masculino" },
  { value: "Feminino", label: "Feminino" }
];
